import { Roboto } from "next/font/google";
import "@/app/globals.css";
import "@/app/globalicons.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { AppContext } from "@/context/AppContext";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "food ordering",
  description: "Generated by food ordering",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="pt-4 px-12">
          <AppContext>
            <Toaster position="bottom-center" />
            <Header />
            {children}
            <Footer />
          </AppContext>
        </main>
      </body>
    </html>
  );
}
